export const GAME_CONFIG = {
  rendering: {
    maxPixelRatio: 1.5,
    fogNear: 18,
    fogFar: 52,
    rebuildsPerFrame: 2,
  },
  world: {
    width: 48,
    height: 28,
    depth: 40,
    chunkSize: 16,
  },
  destruction: {
    punchRadius: 1.9,
    maxPunchVoxels: 50,
    punchRange: 2.7,
    punchCooldown: 0.34,
    groundPoundRadius: 2.8,
    maxGroundPoundVoxels: 80,
    groundPoundVelocity: -14,
    groundPoundCooldown: 0.65,
    hitStop: 0.06,
    blastRadius: 2.4,
    maxBlastVoxels: 40,
  },
  effects: {
    maxDebris: 40,
    maxDust: 24,
    debrisLifetime: 0.9,
  },
  player: {
    moveSpeed: 4.5,
    acceleration: 22,
    airControl: 0.4,
    // Tuned for a readable arc on iPhone: about one second in the air.
    jumpVelocity: 9.5,
    gravity: 18,
    maxFallSpeed: 18,
    radius: 0.32,
    height: 1.4,
    stepHeight: 0.45,
    spawn: { x: 24.5, y: 9.7, z: 6.5 },
    maxHp: 500,
  },
  enemies: {
    maxActive: 4,
    hp: 2,
    moveSpeed: 0.9,
    contactRange: 0.9,
    contactDamage: 1,
    contactCooldown: 1.1,
    knockback: 1.45,
  },
  items: {
    maxCoins: 16,
    pickupRange: 0.9,
    coinValue: 10,
  },
  goal: {
    // ゴールは入口から十分に離れた地下の最終空間へ配置する。
    position: { x: 24.5, y: 9.6, z: 34.5 },
    pickupRange: 1.4,
    requiredDepth: 22,
    requiredDestroyed: 12,
    requiredEnemiesDefeated: 2,
  },
  camera: {
    distance: 11,
    height: 1.55,
    minPitch: -0.4,
    maxPitch: 0.65,
    sensitivity: 0.008,
  },
} as const;
