export const GAME_CONFIG = {
  rendering: {
    maxPixelRatio: 1.5,
    fogNear: 18,
    fogFar: 52,
    rebuildsPerFrame: 2,
  },
  world: {
    width: 48,
    height: 28,
    depth: 40,
    chunkSize: 16,
  },
  destruction: {
    punchRadius: 2.0,
    maxPunchVoxels: 56,
    punchRange: 3.15,
    punchCooldown: 0.29,
    groundPoundRadius: 2.7,
    maxGroundPoundVoxels: 78,
    groundPoundVelocity: -15,
    groundPoundCooldown: 0.72,
    hitStop: 0.052,
    blastRadius: 2.65,
    maxBlastVoxels: 56,
  },
  effects: {
    maxDebris: 48,
    maxDust: 28,
    debrisLifetime: 0.82,
  },
  player: {
    moveSpeed: 5.0,
    acceleration: 28,
    airControl: 0.46,
    jumpVelocity: 9.8,
    gravity: 18,
    maxFallSpeed: 19,
    radius: 0.32,
    height: 1.4,
    stepHeight: 0.22,
    groundProbeDistance: 0.08,
    groundSnapDistance: 0.24,
    spawn: { x: 24.5, y: 9.7, z: 6.5 },
    maxHp: 16,
  },
  enemies: {
    maxActive: 8,
    hp: 3,
    moveSpeed: 0.94,
    contactRange: 0.86,
    contactDamage: 1,
    contactCooldown: 1.35,
    knockback: 1.55,
  },
  items: {
    maxCoins: 20,
    pickupRange: 0.9,
    coinValue: 10,
  },
  goal: {
    position: { x: 24.5, y: 9.6, z: 34.5 },
    pickupRange: 1.4,
    requiredDepth: 22,
    requiredDestroyed: 20,
    requiredEnemiesDefeated: 3,
  },
  run: {
    targetSeconds: 300,
    bossDepthRatio: 0.82,
    bossEarliestSeconds: 210,
    bossForceSeconds: 240,
    maxDepthTiers: 6,
  },
  camera: {
    baseDistance: 8.5,
    minDistance: 1.35,
    maxDistance: 9.5,
    targetHeight: 1.42,
    lookAhead: 0.42,
    cameraCollisionRadius: 0.35,
    collisionHysteresis: 0.14,
    collisionPullOutSpeed: 5.5,
    followSpeed: 19,
    recenterDuration: 0.52,
    manualCooldown: 0.85,
    yawSensitivity: 0.0068,
    pitchSensitivity: 0.0052,
    minPitch: -0.30,
    maxPitch: 0.80,
    defaultPitch: 0.28,
    groundPoundCameraLift: 0.18,
    groundPoundCameraDistance: 0.62,
  },
} as const;
